name: medbuddy
description: Your Medical Partner

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  path: ^1.8.0
  firebase_storage: ^10.2.7
  image_picker: ^0.8.4+6

#.........................................................................

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  geolocator: ^8.2.0
  optimize_battery: ^0.0.4
  google_maps_flutter: ^2.1.3
  latlng: ^0.1.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.4
  http: ^0.13.4
  flutter_restart: ^0.0.3
  firebase_messaging: ^11.2.12
  rxdart: ^0.27.1
  provider: ^6.0.2
  permission_handler: ^9.2.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  curved_navigation_bar: ^1.0.3
  flutter_staggered_animations: ^1.0.0
  webview_flutter: ^3.0.1
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  fluttertoast: ^8.0.9
  intl:
  date_picker_timeline: ^1.2.3
  url_launcher: ^6.0.13
  flutter_rating_bar: ^4.0.0
  blinking_text: ^1.0.2
  firestore_search: ^0.1.9
  get: ^4.6.5
  uuid: ^2.2.2
  flutter_share: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  table_calendar: ^2.2.1
  open_file: ^3.0.3
  syncfusion_flutter_pdf: ^18.4.48-beta
  animated_text_kit: ^3.1.2
  carousel_slider: ^4.1.1
  pay: ^1.0.1
  #agora_uikit: ^1.0.2
  #flutter_stripe: ^2.0.1

  # flutter_svg: 
  flutter_local_notifications:
  # flare_flutter:
  #   git: 
  #     url: https://github.com/2d-inc/Flare-Flutter.git
  #     ref: dev
  #     path: flare_flutter
  flare_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/logo/medbuddy_logo.png"
    



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/splash/delete-unscreen.gif
    - assets/sound/
    - assets/splash/
    - assets/logo/
    - assets/images/login.png
    - assets/
    - assets/images/
    - assets/ads/
    - assets/creatorspic/
    - assets/signup.gif
    - assets/food_delivery.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ic
      fonts:
        - asset: assets/fonts/ic/ic_medicine.ttf
    - family: Icmed
      fonts:
        - asset: assets/fonts/ic/fonts/icofont.ttf
    - family: Angel
      fonts:
        - asset: assets/fonts/neu/Angel Signature.ttf    
    - family: JosefinSans
      fonts:
        - asset: assets\fonts\Josefin_Sans\static\JosefinSans-Light.ttf

    - family: arvoBold
      fonts:
        - asset: assets\fonts\Arvo\Arvo-Bold.ttf

    - family: JosefinSansBI
      fonts:
        - asset: assets\fonts\Josefin_Sans\static\JosefinSans-BoldItalic.ttf
        
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
